version: '3.3'

services:
  db:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    # volumes:
    #   - db_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - wp_data:/var/www/html
    restart: always
    env_file:
      - .env

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wp_data:/var/www/html
    restart: always

volumes:
  wp_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /home/yuohno/data/wordpress
  # db_data:
    # driver: local
    # driver_opts:
    #   type: none
    #   o: bind
    #   device: /home/yuohno/data/mariadb