version: '3.3'

services:
  db:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
      args:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    restart: always
    # env_file: 
    # - .env
    # volumes:
    #   - db_data:/var/lib/mysql

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    # image: wordpress:php7.4-fpm
    build:
      context: ./requirements/wordpress
      dockerfile: Dockerfile
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file:
      - .env
    # environment:
    #   WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
    #   WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
    #   WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
    #   WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'

  nginx:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: Dockerfile
    ports:
      # - "80:80"
      - "443:443"
    volumes:
      - ./requirements/nginx/conf:/etc/nginx/conf.d
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always

volumes:
  # db_data:
  wordpress_data: