version: '3.8'

services:
  db:
    container_name: my-mariadb
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    # volumes:
    #   - db_data:/var/lib/mysql
    env_file:
      - .env

# volumes:
#   db_data: