version: '3.3'

services:
  db:
    container_name: mariadb
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'

  wordpress:
    container_name: wordpress
    depends_on:
      - db
    image: wordpress:php7.4-fpm
    volumes:
      - ./wordpress_data:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: '${WORDPRESS_DB_HOST}'
      WORDPRESS_DB_USER: '${WORDPRESS_DB_USER}'
      WORDPRESS_DB_PASSWORD: '${WORDPRESS_DB_PASSWORD}'
      WORDPRESS_DB_NAME: '${WORDPRESS_DB_NAME}'

  nginx:
    image: nginx
    container_name: wordpress-nginx-
    ports:
      # - "80:80"
      - "8080:8080"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always

volumes:
  db_data:
  # wordpress_data:
