version: '3.1'

services:
  db:
    image: mariadb
    # volumes:
    #   - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env
    # environment:
    #   MYSQL_ROOT_PASSWORD: somewordpress
    #   MYSQL_DATABASE: wordpress
    #   MYSQL_USER: wordpress
    #   MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    container_name: my-wordpress
    build: .
    # ports:
    #   - "8000:80"
    restart: always
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    # environment:
    #   WORDPRESS_DB_HOST: db:3306
    #   WORDPRESS_DB_USER: wordpress
    #   WORDPRESS_DB_PASSWORD: wordpress
    #   WORDPRESS_DB_NAME: wordpress

  nginx:
    # image: nginx
    build:
      context: ../nginx/
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "443:443"
      # - "8000:80"
      # - "8080:8080"
    volumes:
      # - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ../nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    restart: always

volumes:
  wordpress_data : {}
  # db_data: {}
